;/*!jsx/modules/nav.jsx*/
define("jsx/modules/nav.jsx",function(e,a,t){"use strict";var c=React.createClass({displayName:"Nav",getInitialState:function(){var e={};return e[this.props.page]="choose",{cls:e}},changeNav:function(e){var a={};a[e]="choose",this.setState({cls:a}),this.props.parentChangePage(e)},render:function(){var e=this.state.cls;return React.createElement("div",{className:"header navbar navbar-static-top"},React.createElement("div",{className:"container"},React.createElement("div",{className:"navbar-header"},React.createElement("a",{className:"navbar-brand",onClick:this.changeNav.bind(this,"home")},"Bootstrap")),React.createElement("ul",{className:"navbar-nav nav nav-pills pull-right"},React.createElement("li",null,React.createElement("a",{href:""},"Bootstrap中文网"))),React.createElement("ul",{className:"navbar-nav nav nav-pills"},React.createElement("li",null,React.createElement("a",{className:e.start,onClick:this.changeNav.bind(this,"start")},"起步")),React.createElement("li",null,React.createElement("a",{className:e.css,onClick:this.changeNav.bind(this,"css")},"全局css样式")),React.createElement("li",null,React.createElement("a",{className:e.component,onClick:this.changeNav.bind(this,"component")},"组件")),React.createElement("li",null,React.createElement("a",{className:e.js,onClick:this.changeNav.bind(this,"js")},"Javascript插件")),React.createElement("li",null,React.createElement("a",{className:e.marker,onClick:this.changeNav.bind(this,"marker")},"定制")),React.createElement("li",null,React.createElement("a",{href:""},"网站实例")))))}});t.exports=c});
;/*!jsx/pages/home.jsx*/
define("jsx/pages/home.jsx",function(e,t,a){"use strict";var s=React.createClass({displayName:"Home",getInitialState:function(){return{firstList:[{img:"img/sass-less.png",h3:"预处理脚本",p:'虽然可以直接使用 Bootstrap 提供的 CSS 样式表，不要忘记 Bootstrap 的源码是基于最流行的 CSS 预处理脚本 - <a href="">Less</a> 和 <a href="">Sass</a> 开发的。你可以采用预编译的 CSS 文件快速开发，也可以从源码定制自己需要的样式。'},{img:"img/devices.png",h3:"一个框架、多种设备",p:"你的网站和应用能在 Bootstrap 的帮助下通过同一份代码快速、有效适配手机、平板、PC 设备，这一切都是 CSS 媒体查询（Media Query）的功劳。"},{img:"img/components.png",h3:"特性齐全",p:"Bootstrap 提供了全面、美观的文档。你能在这里找到关于 HTML 元素、HTML 和 CSS 组件、jQuery 插件方面的所有详细文档。"}],secondList:[{img:"img/01.png"},{img:"img/02.jpg"},{img:"img/03.png"},{img:"img/04.png"}]}},createList:function(e){return e.map(function(e,t){if(e.h3){var a={__html:e.p};return React.createElement("li",{key:t},React.createElement("img",{src:e.img,alt:""}),React.createElement("h3",null,e.h3),React.createElement("p",{dangerouslySetInnerHTML:a}))}return React.createElement("li",{key:t},React.createElement("img",{src:e.img,alt:""}))})},render:function(){return React.createElement("section",{className:"home",style:{display:this.props.show}},React.createElement("div",{className:"banner"},React.createElement("div",{className:"big-logo"},"B"),React.createElement("h1",null,"Bootstrap 是最受欢迎的 HTML、CSS 和 JS 框架，用于开发响应式布局、移动设备优先的 WEB 项目。"),React.createElement("span",{className:"btn btn-lg"},"下载Bootstrap"),React.createElement("p",{className:"info"},"当前版本： v3.3.7 | 文档更新于：2017-05-22")),React.createElement("div",{className:"first-list"},React.createElement("div",{className:"container"},React.createElement("h2",{className:"title"},"为所有开发者、所有应用场景而设计。"),React.createElement("p",{className:"info"},"Bootstrap 让前端开发更快速、简单。所有开发者都能快速上手、所有设备都可以适配、所有项目都适用。"),React.createElement("div",{className:"line"}),React.createElement("ul",{className:"clearfix"},this.createList(this.state.firstList)),React.createElement("div",{className:"line"}),React.createElement("p",{className:"description"},"Bootstrap 是完全开源的。它的代码托管、开发、维护都依赖 GitHub 平台。"),React.createElement("span",{className:"btn btn-lg"},"查看GItHub项目主页"))),React.createElement("div",{className:"second-list"},React.createElement("div",{className:"container"},React.createElement("h2",{className:"title"},"基于 Bootstrap 构建的网站"),React.createElement("p",{className:"info"},"全球数以百万计的网站都是基于 Bootstrap 构建的。你可以先参观一下我们提供的",React.createElement("a",{href:""},"实例精选"),"或者看一看我们粉丝的网站吧。"),React.createElement("div",{className:"line"}),React.createElement("ul",{className:"clearfix"},this.createList(this.state.secondList)),React.createElement("div",{className:"line"}),React.createElement("p",{className:"description"},"我们在“优站精选”里展示了许多精美的 Bootstrap 网站。"),React.createElement("span",{className:"btn btn-lg"},"逛一逛“优站精选”"))))}});a.exports=s});
;/*!jsx/modules/banner.jsx*/
define("jsx/modules/banner.jsx",function(e,t,a){"use strict";var n=React.createClass({displayName:"Banner",render:function(){return React.createElement("div",{className:"banner"},React.createElement("div",{className:"container"},React.createElement("h2",null,this.props.title),React.createElement("p",null,this.props.info)))}});a.exports=n});
;/*!jsx/modules/aside.jsx*/
define("jsx/modules/aside.jsx",function(e,t,a){"use strict";var r=React.createClass({displayName:"Aside",getDefaultProps:function(){return{data:[]}},createList:function(){return this.props.data.map(function(e,t){return React.createElement("li",{key:t},React.createElement("a",{href:"#"+e.id},e.title))})},render:function(){return React.createElement("aside",{className:"aside"},React.createElement("ul",null,this.createList()))}});a.exports=r});
;/*!jsx/modules/article.jsx*/
define("jsx/modules/article.jsx",function(e,t,a){"use strict";var r=React.createClass({displayName:"Article",getDefaultProps:function(){return{data:[]}},createList:function(){return this.props.data.map(function(e,t){return React.createElement("li",{key:t,id:e.id},React.createElement("h3",null,e.title),React.createElement("p",null,e.content))})},render:function(){return React.createElement("article",{className:"article"},React.createElement("ul",null,this.createList()))}});a.exports=r});
;/*!jsx/modules/content.jsx*/
define("jsx/modules/content.jsx",function(e,t,a){"use strict";var s=e("jsx/modules/aside.jsx"),n=e("jsx/modules/article.jsx"),r=React.createClass({displayName:"Content",getDefaultProps:function(){return{data:[]}},render:function(){return React.createElement("div",{className:"content container"},React.createElement(s,{data:this.props.data}),React.createElement(n,{data:this.props.data}))}});a.exports=r});
;/*!jsx/mixins/util.jsx*/
define("jsx/mixins/util.jsx",function(e,t,n){"use strict";var s={ajax:function(e,t){var n=new XMLHttpRequest;n.onreadystatechange=function(){4===n.readyState&&200===n.status&&t(JSON.parse(n.responseText))},n.open("GET",e,!0),n.send(null)}};n.exports=s});
;/*!jsx/pages/page.jsx*/
define("jsx/pages/page.jsx",function(t,e,s){"use strict";var a=t("jsx/modules/banner.jsx"),i=t("jsx/modules/content.jsx"),n=t("jsx/mixins/util.jsx"),o=React.createClass({displayName:"Page",mixins:[n],getInitialState:function(){return{data:[]}},render:function(){return React.createElement("section",{className:"section",style:{display:this.props.show}},React.createElement(a,{title:this.props.title,info:this.props.info}),React.createElement(i,{data:this.state.data}))},componentDidMount:function(){this.ajax(this.props.url,function(t){t&&this.setState({data:t})}.bind(this))}});s.exports=o});
;/*!jsx/app.jsx*/
define("jsx/app.jsx",function(e,t,a){"use strict";var s=e("jsx/modules/nav.jsx"),n=e("jsx/pages/home.jsx"),r=e("jsx/pages/page.jsx"),o=React.createClass({displayName:"App",propTypes:{page:React.PropTypes.string.isRequired},getInitialState:function(){var e={home:"none",start:"none",css:"none",component:"none",js:"none",marker:"none"};return e[this.props.page]="block",{page:e}},getCurrentPage:function(){for(var e in this.state.page)if("block"===this.state.page[e])return e},changePage:function(e){for(var t in this.state.page)this.state.page[t]="none";this.state.page[e]="block",this.setState({page:this.state.page})},render:function(){var e=this.state.page;return React.createElement("div",null,React.createElement(s,{page:this.getCurrentPage(),parentChangePage:this.changePage}),React.createElement(n,{show:e.home}),React.createElement(r,{show:e.start,title:"起步",info:"简要介绍 Bootstrap，以及如何下载、使用，还有基本模版和案例，等等。",url:"data/start.json"}),React.createElement(r,{show:e.css,title:"全局 CSS 样式",info:"设置全局 CSS 样式；基本的 HTML 元素均可以通过 class 设置样式并得到增强效果；还有先进的栅格系统。",url:"data/css.json"}),React.createElement(r,{show:e.component,title:"组件",info:"无数可复用的组件，包括字体图标、下拉菜单、导航、警告框、弹出框等更多功能。",url:"data/component.json"}),React.createElement(r,{show:e.js,title:"JavaScript 插件",info:"jQuery 插件为 Bootstrap 的组件赋予了“生命”。可以简单地一次性引入所有插件，或者逐个引入到你的页面中。",url:"data/js.json"}),React.createElement(r,{show:e.marker,title:"定制并下载 Bootstrap",info:"通过自定义 Bootstrap 组件、Less 变量和 jQuery 插件，定制一份属于你自己的 Bootstrap 版本吧。",url:"data/marker.json"}))}});a.exports=o});
;/*!jsx/bootsrap.jsx*/
define("jsx/bootsrap.jsx",function(e){"use strict";var a=e("jsx/app.jsx");ReactDOM.render(React.createElement(a,{page:"home"}),app)});